import {
  Atom,
  Triangle,
  Component,
  FileType2,
  Coffee,
  Leaf,
  MonitorSmartphone,
  Hash,
  FileCode2,
  Smartphone,
  Layers,
  PenTool,
  CreditCard,
  Boxes,
  Languages,
  Eye,
  TrendingUp,
  Cpu,
  Search,
  FileText,
  ShieldCheck,
  Target,
  ListChecks,
  UploadCloud,
  Megaphone,
  MessagesSquare,
  Mail,
  Newspaper,
  Image,
  Palette,
  Globe,
  Send,
  BarChart3,
  Volume2,
  PhoneCall,
  Radio,
  Clock,
  PanelsTopLeft,
  Images,
  CalendarClock,
  Activity,
  MousePointerClick,
  Users,
  Bot,
  Vote,
  Share2,
  Cloud,
  Container,
  GitBranch,
  Server,
  Sparkles,
  KeyRound,
  Database,
  Zap,
} from "lucide-react";

// Ordered list of [regex, Icon] pairs. First match wins, so more specific
// keywords should be listed before generic ones.
const RULES = [
  [/react native/i, Smartphone],
  [/react/i, Atom],
  [/next\.?js/i, Triangle],
  [/vue|nuxt/i, Component],
  [/typescript/i, FileType2],
  [/java(?!script)/i, Coffee],
  [/spring/i, Leaf],
  [/electron|desktop/i, MonitorSmartphone],
  [/\.net|c#/i, Hash],
  [/python|django/i, FileCode2],
  [/flutter/i, Layers],
  [/ui design|prototyp/i, PenTool],
  [/payment/i, CreditCard],
  [/inventory/i, Boxes],
  [/natural language|nlp/i, Languages],
  [/computer vision|vision/i, Eye],
  [/predictive|analytics/i, TrendingUp],
  [/tensorflow|pytorch|machine learning|deep learning|model/i, Cpu],
  [/tender research|tender search/i, Search],
  [/proposal|documentation/i, FileText],
  [/compliance/i, ShieldCheck],
  [/strategic bidding|bid management|bidding/i, Target],
  [/submission/i, ListChecks],
  [/content creation|content marketing|blog|article/i, Newspaper],
  [/community/i, Users],
  [/targeted advertising|ppc|targeting/i, MousePointerClick],
  [/core web vitals/i, Activity],
  [/seo/i, Search],
  [/social media graphics|graphics/i, Image],
  [/social media/i, Share2],
  [/email/i, Mail],
  [/logo|branding/i, Palette],
  [/website assets|website/i, Globe],
  [/sms|delivery/i, Send],
  [/sender id/i, KeyRound],
  [/detailed reports|reports|real-time reports/i, BarChart3],
  [/api/i, Zap],
  [/contact/i, Users],
  [/audio/i, Volume2],
  [/dialing|voice/i, PhoneCall],
  [/regional language/i, Languages],
  [/capacity|platform/i, Radio],
  [/panel/i, PanelsTopLeft],
  [/multimedia/i, Images],
  [/scheduling/i, CalendarClock],
  [/tracking|status/i, Activity],
  [/upload/i, UploadCloud],
  [/interactive|buttons/i, MousePointerClick],
  [/rich media/i, Images],
  [/personalized/i, Target],
  [/communication/i, MessagesSquare],
  [/chatbot/i, Bot],
  [/voter/i, Vote],
  [/broadcasting/i, Megaphone],
  [/sentiment/i, Activity],
  [/strategy/i, Target],
  [/ios|android/i, Smartphone],
  [/node\.?js/i, Server],
  [/saas/i, Cloud],
  [/llm|rag/i, Sparkles],
  [/aws|azure/i, Cloud],
  [/docker/i, Container],
  [/kubernetes/i, Boxes],
  [/ci\/cd/i, GitBranch],
  [/whatsapp/i, MessagesSquare],
  [/design system/i, Layers],
  [/prototype/i, PenTool],
  [/identity/i, Palette],
  [/state management/i, Database],
  [/qa|launch/i, ShieldCheck],
];

export function getTagIcon(text = "") {
  for (const [pattern, Icon] of RULES) {
    if (pattern.test(text)) return Icon;
  }
  return Sparkles;
}
